name: Build Strauss Applications

on:
  workflow_dispatch:

jobs:

  build-linux:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install

      - name: Build Linux application
        run: npm run dist:linux

      - name: Upload Linux artifact
        uses: actions/upload-artifact@v4
        with:
          name: Strauss-Linux
          path: release/*.AppImage


  build-macos:

    runs-on: macos-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install

      - name: Build macOS application
        run: npm run dist:mac

      - name: Upload macOS artifact
        uses: actions/upload-artifact@v4
        with:
          name: Strauss-macOS
          path: release/*.dmg