name: Build Strauss Applications

on:
  workflow_dispatch:

jobs:

  build-linux:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4


      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"


      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r StraussModule/python_core/requirements.txt
          pip install pyinstaller


      - name: Build Linux backend
        working-directory: StraussModule/python_core
        run: |
          pyinstaller StraussBackend.spec


      - name: Prepare Linux backend
        run: |
          mkdir -p backends/linux
          mv StraussModule/python_core/dist/StraussBackend \
             backends/linux/StraussBackend-linux


      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22


      - name: Install Node dependencies
        run: npm install


      - name: Build Linux application
        run: npm run dist:linux


      - name: Upload Linux artifact
        uses: actions/upload-artifact@v4
        with:
          name: Strauss-Linux
          path: release/*.AppImage


  build-macos:

    runs-on: macos-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4


      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"


      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r StraussModule/python_core/requirements.txt
          pip install pyinstaller


      - name: Build macOS backend
        working-directory: StraussModule/python_core
        run: |
          pyinstaller StraussBackend.spec


      - name: Prepare macOS backend
        run: |
          mkdir -p backends/mac
          mv StraussModule/python_core/dist/StraussBackend \
             backends/mac/StraussBackend-macos


      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22


      - name: Install Node dependencies
        run: npm install


      - name: Build macOS application
        run: npm run dist:mac


      - name: Upload macOS artifact
        uses: actions/upload-artifact@v4
        with:
          name: Strauss-macOS
          path: release/*.dmg